#!/system/bin/sh

separ_img()
{
 size_sup="$(lpdump --slot=0 /data/local/UnpackerQfil/"$file" | busybox awk '/Size:/ { print $2 }')"
 piece_size="$(busybox expr "$(busybox expr "$(busybox expr "$size_sup" / 1024 / 1024)" \+ "$num" - 1)" / "$num")"

if busybox test "$(busybox expr "$size_sup" \* 1 2> /dev/null)"; then
if busybox test "$(busybox expr "$piece_size" \* 1 2> /dev/null)"; then
 busybox find -maxdepth 1 -name "*.img.[0-9]*" -exec busybox rm -f {} \;
 clear
 echo
 echo ".....Размер $file: "$size_sup" байт"
 echo ".....Размер части: "$piece_size" Mb"
 echo ".....Количество частей: $num"
 echo
 echo ".....Выполняем разделение $file..."

 chunk_split -s .%d -B 4K -C "$piece_size"M "$file"

if [ $(echo $?) -eq 0 ]; then
 echo 
 echo ".....Успешно завершено!"
 echo ".....Сохранено в /data/local/UnpackerQfil"
 echo
 busybox find -maxdepth 1 -name "*.img.[0-9]" | busybox sort -n | while read a; do
 ss="$(expr "${a##*.}" - 1)"
 busybox mv "$a" super.img."$ss"
done
 busybox find -maxdepth 1 -name "*.img.[0-9][0-9]" | busybox sort -n | while read a; do
 ss="$(expr "${a##*.}" - 1)"
 busybox mv "$a" super.img."$ss"
 done
 return
else
 echo
 echo ".....Ошибка при выполнении!"
 echo
 busybox find -maxdepth 1 -name "*.img.[0-9]*" -exec busybox rm -f {} \;
fi
else
echo
echo ".....Ошибка значения количества частей!"
echo
fi
else
echo
echo ".....Ошибка определения размера $file!"
echo
fi
return
}


 input_piece()
{
 echo
 echo ".....Введите количество частей, на которые нужно разделить $file:"
 echo
 read n
if busybox test "$(busybox expr "$n" \* 1 2> /dev/null)"; then
 num="$n"
 separ_img
 else
 echo
 echo ".....Значение неверно, введите заново..."
 input_piece
fi
 return
}
 input_piece
